### ISSUE TITLE
Introduce a third (Enterprise) FF Cloud Tier

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowforge#2653]
Configuration of a third Enterprise tier (analogous to "Teams") with two exclusive features:

- SSO (currently configurable via Admin, so no User-Teams interaction possible)
- HA

```[tasklist]
### Tasks
- [x] Migration of specific Teams to the new Tier
- [x] Decide on Enterprise pricing
- [ ] https://github.com/flowforge/CloudProject/issues/207
```

**Comment by knolleary** [comment]
We need to decide how to handle any existing 'Teams' teams that have turned on HA already.

If we turn off HA in the Teams tier and make it Enterprise only, that will leave those users stuck.

Options:

1. If the HA feature flag is disabled for a TeamType, but we find an instance with it enabled, allow the user to disable HA on that instance, but do not allow them to enable.
2. Find a way to administratively override feature flags for individual teams

Option 1 is probably the cleanest approach to take.


---

As for SSO - given there is no configuration within the Team regarding SSO, this is purely for us as admins to control who gets the feature enabled.

**Comment by MarianRaphael** [comment]
Only one team (besides the FF Team) is affected. If this team is currently not in the "Teams" tier, we could maintain the migration path we used for the last migration. Otherwise, I would go with option 1.
